### PR TITLE
Add support for regex detecting

### PR DESCRIPTION
**Pull request by tjbcg**
This will allow the bot to detect messages matching regexes in regexDatabase. 
Exemple useage : detect recurrent messages like "Hi !", and answer them.

### CODE REVIEW

**Comment by henopied** [comment]
that would be cool!

**Comment by Apostolique** [comment]
That's cool!

**Comment by Apostolique** [comment]
BTW, do you think we should rename the project? Apos is the prefix I use for my personal projects, but maybe you'd rather the project get a new name?

**Comment by tjbcg** [comment]
If you use Apos prefix for personnal project, then free to you to choose wether or not this is a personnal one. You may change the name to something like `PyTwitchBot` (py for python) or even change it to somthing like `python-twitch-bot`. These are just suggestion :smile:

**Pull request merged**
